#!/bin/bash

wal -R

. ~/.cache/wal/colors.sh

pgrep -x sxhkd >/dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

#removing all rules
bspc rule -r '*'

bspc monitor -d term web III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

#changing colors
bspc config normal_border_color $background
bspc config active_border_color $color5
bspc config focused_border_color $color5
bspc config presel_feedback_color $color5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc rule -a librewolf-default desktop='^2' follow=on
bspc rule -a Emacs state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

~/.config/bspwm/autostart > /tmp/autostart-bspwm-log &

#this is for java applications to work properly
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix cursor
xsetroot -cursor_name left_ptr
